CREATE TABLE IF NOT EXISTS listings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nft_id TEXT DEFAULT '',
  nft_tx_sig TEXT DEFAULT '',
  tx_sig TEXT DEFAULT '',
  nft TEXT DEFAULT '',
  seller TEXT DEFAULT '',
  active INTEGER DEFAULT 0 ,
  min_price INTEGER DEFAULT 0
);
