CREATE TABLE IF NOT EXISTS transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  signature TEXT NOT NULL UNIQUE,

  tx TEXT NOT NULL,

  onchain INTEGER DEFAULT 1,

  block_id INTEGER DEFAULT 0,
  block_hash TEXT DEFAULT '',
  transaction_id INTEGER DEFAULT 0,

  created_at INTEGER DEFAULT 0
);
