name: build

on:
  push:
    branches: [ develop, staging, master ]
  pull_request:
    branches: [ develop, staging, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'v0.12.1'
      - name: Check Formatting
        run: cargo fmt --check --verbose
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      #- name: Install wasm-pack
      #  run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Compile into WASM
        working-directory: ./saito-wasm
        run: wasm-pack build --debug --target browser
#      - name: Build documentation
#        run: cargo doc --no-deps
