CREATE TABLE IF NOT EXISTS gms (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  publickey TEXT NOT NULL,
  day INTEGER NOT NULL,
  sig TEXT NOT NULL UNIQUE,
  ts INTEGER NOT NULL,
  block_id INTEGER DEFAULT 0,
  UNIQUE (publickey, day)
);
