name: Run E2E Tests

on:
  push:
    branches:
      - develop
      - master
      - prod
  pull_request:
    branches:
      - develop
      - master
      - prod

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: bash ./rust/scripts/bootstrap_for_ci.sh
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: ./rust/saito-wasm/package-lock.json

      - name: saito-wasm npm install
        run: npm install
        working-directory: ./rust/saito-wasm

      - name: Wasm Build
        run: npm run build-prod
        working-directory: ./rust/saito-wasm

      - name: link saito-wasm
        run: npm link
        working-directory: ./rust/saito-wasm

      - name: Install npm packages for saito-js
        run: npm install
        working-directory: ./rust/saito-js

      - name: link saito-wasm to saito-js
        run: npm link saito-wasm
        working-directory: ./rust/saito-js

      - name: build saito-js
        run: npm run build
        working-directory: ./rust/saito-js

      - name: copy saito-js build artifacts
        run: |
          cp package.json dist
          cp package-lock.json dist
          cp tsconfig.json dist
          cp .npmignore dist
        working-directory: ./rust/saito-js

      - name: npm install in saito-js dist
        run: npm install
        working-directory: ./rust/saito-js/dist

      - name: link saito-wasm in saito-js dist
        run: npm link saito-wasm
        working-directory: ./rust/saito-js/dist

      - name: link saito-js
        run: npm link
        working-directory: ./rust/saito-js/dist

      - name: Install node/ dependencies
        run: npm install
        working-directory: ./node

      - name: link saito-js to node
        run: npm link saito-js
        working-directory: ./node

      - name: Build Rust binary
        run: cargo build --release -p saito-rust
        working-directory: ./rust

      - name: Install e2e dependencies
        run: npm install
        working-directory: ./e2e

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 7
