name: Unit Test Plan

on:
  push:
    branches: [ master, prod ]
  pull_request:
    branches: [ develop, master, staging ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: rust/saito-wasm/package-lock.json
      - name: Check Formatting (RUST)
        run: cargo fmt --check --verbose
        working-directory: ./rust
      - name: Check Formatting (JS)
        run: npx prettier --check ./lib
        working-directory: ./node
      - name: Build
        run: cargo build --verbose
        working-directory: ./rust
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./rust
      - name: Install WASM toolchain
        run: bash ./scripts/bootstrap_for_ci.sh
        shell: bash
        working-directory: ./rust
      - name: Install saito-wasm npm packages
        run: npm install
        working-directory: ./rust/saito-wasm
      - name: Compile into WASM
        working-directory: ./rust/saito-wasm
        run: npm run build
      - name: Compile JS code
        run: npm install && npm run reset
        working-directory: ./node
#      - name: Build documentation
#        run: cargo doc --no-deps
