name: Unit Test Plan

on:
  push:
    branches: [ master, prod ]
  pull_request:
    branches: [ develop, master, staging ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'v0.12.1'
      - name: Check Formatting (RUST)
        run: cargo fmt --check --verbose
        working-directory: ./rust
      - name: Check Formatting (JS)
        run: npx prettier --check ./lib
        working-directory: ./node
      - name: Build
        run: cargo build --verbose
        working-directory: ./rust
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./rust
      #- name: Install wasm-pack
      #  run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Compile into WASM
        working-directory: ./rust/saito-wasm
        run: wasm-pack build --debug --target browser
      - name: Compile JS code
        run: npm install && npm run reset
        working-directory: ./node
#      - name: Build documentation
#        run: cargo doc --no-deps
